version: '2'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./wp-app:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: gratuitousleaches
    group_add:
      - www-data
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7.22
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gratuitousleaches
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: gratuitousleaches
    networks:
      - back
      
networks:
  back:
volumes:
  db_data: